"""tracker table

Revision ID: 6c03de58369e
Revises: 6a791cbd3198
Create Date: 2020-03-19 19:28:37.505795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c03de58369e'
down_revision = '6a791cbd3198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tracker', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracker', type_='foreignkey')
    op.drop_column('tracker', 'user_id')
    # ### end Alembic commands ###
